USE adlister_db;

DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(240) UNIQUE NOT NULL,
    email VARCHAR(240) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ads (
    ad_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    title VARCHAR(240) NOT NULL,
    price DOUBLE UNSIGNED DEFAULT 0.00 NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY (ad_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE categories(
  cat_id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
  cat_name VARCHAR(250) NOT NULL,
  PRIMARY KEY(cat_id)
);

CREATE TABLE ad_category(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ad_id INT UNSIGNED NOT NULL, 
  cat_id INT UNSIGNED NOT NULL, 
  FOREIGN KEY(ad_id) REFERENCES  ads(ad_id),
  FOREIGN KEY(cat_id) REFERENCES categories(cat_id),
  PRIMARY KEY(id)
);

ALTER TABLE users ADD UNIQUE (username);
ALTER TABLE users ADD UNIQUE (email);


